adding comments

diff --git a/week1/stats b/week1/stats
--- a/week1/stats
+++ b/week1/stats
@@ -3,24 +3,27 @@
 # some global variables
 PROGNAME=$(basename $0)
 datafilepath="datafile$$"
-averages=()
-medians=()
-allfields=()
+averages=()					# an array to store averages
+medians=()					# an array to store medians
+allfields=()				# an array to keep all fields in file
 
 clean_up() {
 	#------------------------------------------------------------------
-	# Delete temporary file if it exists
+	# Delete temporary file if it exists and exit with code $1 (0 or 1)
 	#
 	# Use "datafile$$" explicitly as that is the only file we would want
 	# to delete
 	#------------------------------------------------------------------
 	if [ -e "datafile$$" ]; then
-		rm -f "datafile$$"
+		rm -f "datafile$$" # force removal of datafile if it exists
 	fi
 	exit $1
 }
 
 clean_up_trap() {
+	#------------------------------------------------------------------
+	# Clean up and exit with an error
+	#------------------------------------------------------------------
 	clean_up 1
 }
 
@@ -32,25 +35,37 @@ exit_prog() {
 	# $1 is the message
 	#------------------------------------------------------------------
 
-	>&2 echo $1  # >$2 outputs stderr to stdout
-	clean_up 1
+	>&2 echo $1 # >$2 outputs stderr to stdout
+	clean_up 1 	# exit with error code
 }
 
 usage() {
+	#------------------------------------------------------------------
+	# Print instructions and exit with an error code
+	#------------------------------------------------------------------
 	exit_prog "Usage: stats {-rows|-cols} [file]"
 }
 
 no_data() {
+	#------------------------------------------------------------------
+	# Exit with an error message and code
+	#------------------------------------------------------------------
 	exit_prog "${PROGNAME}: no data in file"
 }
 
 bad_file() {
+	#------------------------------------------------------------------
+	# Exit with an error message and code
+	# $1 is an unreadable filename
+	#------------------------------------------------------------------
 	exit_prog "${PROGNAME}: cannot read '$1'"
 }
 
 check_opts() {
 	#------------------------------------------------------------------
-	# Check whether the user entered a valid option, otherwise exit
+	# Check whether the user entered a valid option, otherwise exit.
+	# Valid options are any strings beginning with 'r' or any words beginning
+	# with 'c'
 	#
 	# $1 is the supposed option
 	#------------------------------------------------------------------
@@ -64,7 +79,7 @@ avg() {
 	#------------------------------------------------------------------
 	# Produce an average given a total and number of fields
 	# with help from -- http://stackoverflow.com/questions/2395284/round-a-divided-number-in-bash
-	# (total + (denom/2)) / denom to round up on halves or higher
+	# ((total + (denom/2)) / denom) to round up on halves or higher
 	#------------------------------------------------------------------
 	local total=$1
 	local fields=$2
@@ -99,7 +114,7 @@ do_calculations() {
 	# and inner reps, and 1 for inner increment
 	#
 	# For columns reverse the outer and inner: pass field count for outer 
-	# reps, 1 for outer increment, total fields for inner reps
+	# reps, 1 for outer increment, total fields for inner reps, and
 	# field count for inner increment 
 	#------------------------------------------------------------------
 	local count=0
@@ -109,31 +124,31 @@ do_calculations() {
 	local inner_inc=$4
 	local divisor=$5
 	local roundup=2
-	local med_divisor=$divisor
+	local med_divisor=$divisor # use for determining median number
 
 	for (( i = 0; i < outer_reps; i+=outer_inc )); do
-		total=0
-		thisline=""
-		med_divisor=$divisor
+		total=0		# for a running total
+		thisline="" # a string of all non-zero numbers to be sorted later for median
+		med_divisor=$divisor # needs to be re-assigned every pass to get accurate field count for median
 
-		# reassemble line
+		## reassemble a string from array and get a total sum of line/column
 		for (( x = 0; x < inner_reps; x+=inner_inc )); do
 			idx=$(( $i + $x ))
-			if [[ ${allfields[$idx]} > 0 ]]; then
+			if [[ ${allfields[$idx]} > 0 ]] || [[ ${allfields[$idx]} < 0 ]]; then # number is non-zero
 				# create a column of numbers as a string
 				thisline="$thisline\n${allfields[$idx]}" 
 			else # number is 0 so don't include in median computation
-				med_divisor=$(( $med_divisor-1 ))
+				med_divisor=$(( $med_divisor-1 )) # subtract one from the field count/divisor
 			fi
-			total=$(( ${allfields[$idx]} + $total ))
+			total=$(( ${allfields[$idx]} + $total )) # keep a running total
 		done
 
-		# roundup should be 1 for odd field counts and 2 for even ones
+		## roundup should be 1 for odd field counts and 2 for even ones
 		if [[ "$(( $med_divisor % 2 ))" > 0 ]]; then
 			roundup=1
 		fi
 
-		# figure average for thisline and store in averages array
+		# figure average for current line/row and store in averages array
 		averages[$count]=$(avg $total $divisor)
 		
 		# process median
@@ -151,6 +166,8 @@ do_calculations() {
 printrows() {
 	echo "Averages Medians"
 	for (( i = 0; i < ${#averages[@]}; i++ )); do
+		## print your averages and medians separated with a tab and 1 space
+		## a tab will be 8 spaces on most consoles
 		echo -e "${averages[$i]}\t ${medians[$i]}"
 	done
 }
@@ -176,12 +193,16 @@ trap clean_up_trap SIGINT SIGTERM SIGHUP SIGKILL SIGSTOP
 # figure out whether you have a file or stdin
 case $# in
 1) # if there is only one arg
-	check_opts $1 # get out of the program if you've got a bad option
+	# get out of the program if you've got a bad option
+	check_opts $1 
+	
 	# help here: http://stackoverflow.com/questions/5710957/bash-input-from-pipe
 	# check whether input is from a pipe; if it isn't, it means you either weren't passed a file or weren't passed an option
 	if [ "$( tty )" == 'not a tty' ]; then # it's from a pipe!
+		# so save your information in the temporary file (created here)
 		cat > "$datafilepath"
 	else
+		# print instructions and exit
 		usage
 	fi
 	;;
@@ -190,6 +211,7 @@ case $# in
 	if [ -e $2 ] && [ -r $2 ]; then # file exists and is readable
 		datafilepath=$2
 	else
+		# print an error message and exit
 		bad_file $2
 	fi
 	;;
@@ -198,23 +220,24 @@ case $# in
 	;;
 esac
 
-lc=$(cat $datafilepath | wc -l) # line count
-fct=$(head -n 1 $datafilepath | wc -w) # field count; just count first line of file
+lc=$(cat $datafilepath | wc -l) 		# line count
+fct=$(head -n 1 $datafilepath | wc -w) 	# field count; just count fields in first line of file
 
 ## put all fields from file into an array while there are still tabs
-ct=0
+ct=0 # index for array
 while IFS=$'\t' read -ra fields
 do
 	for i in "${fields[@]}"; do
 		allfields[ct]=$i
 		((ct++))
 	done
-	# if ct is 0, that means there was no good data in the file; print usage and exit
 done < $datafilepath # read in from the file
 
+# if ct is 0, that means there was no good data in the file; print error and exit
 if [[ $ct == 0 ]]; then
 	no_data
 fi
+
 ## do calculations for either rows or columns
 tot_fields=$(( $lc * $fct ))
 case $1 in
@@ -231,5 +254,5 @@ case $1 in
 		;;
 esac
 
-## clean up with no errors
+## clean up and exit with no errors
 clean_up 0
